spring:
  banner:
    location: classpath:banner.txt
    
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/major_project
    password: amilgupta
  jpa:
    hibernate:
      ddl-auto: update
      
jwt:
  public-key: classpath:/config/public.key
  private-key: classpath:/config/private.key

server:
  port: 8081